Improve RequestToInput performance in Check call
fluxninja/aperture pull request #1712
Opened 2023-04-08 17:05 UTC by DariaKunoichi

### Description of change
Closes: GH-903
Closes: GH-880

##### Checklist

- [x] Tested in playground or other setup
- [ ] Screenshot (Grafana) from playground added to PR for 15+ minute run
- [ ] Documentation is changed or added
- [ ] Tests and/or benchmarks are included
- [ ] Breaking changes

2023-04-08 17:05 UTC, DariaKunoichi commented
Check call marked before:
![obraz](https://user-images.githubusercontent.com/88393714/230733942-c5c822a0-4f7e-4579-8e4d-e1eafe7fe143.png)

and after:
![obraz](https://user-images.githubusercontent.com/88393714/230733946-b0079131-4c97-4fdd-9e90-1fa2ad99a255.png)

2023-04-10 18:16 UTC, harjotgill commented on pkg/policies/flowcontrol/service/checkhttp/checkhttp.go
>  }
@openai generate test plan for this function.

2023-04-10 18:18 UTC, harjotgill commented on pkg/policies/flowcontrol/service/checkhttp/checkhttp.go
>  }
generate code for this test plan.

2023-04-12 11:03 UTC, krdln requested changes
I think usage of Object is unnecessary here – you need to wrap everything in NewTerm because of that. Using ValueMap would avoid it.

2023-04-12 11:05 UTC, krdln commented on pkg/policies/flowcontrol/service/checkhttp/checkhttp.go
>  			}
@openai No

2023-04-12 11:37 UTC, krdln commented on pkg/policies/flowcontrol/resources/classifier/classification-engine.go
> +		}
Interestingly, I don't see this ValueToInterface showing up in profiles, but let's avoid doing this unless necessary anyway.

2023-04-12 11:38 UTC, krdln commented on pkg/policies/flowcontrol/resources/classifier/classification-engine.go
> +		log.Errorf("failed to convert value to interface: %v", err)
Nit: `log.Bug()` would be more appropriate perhaps? (So that we're not spammed by logs if this happens on man requests)

2023-04-12 11:47 UTC, krdln commented
Profile looks really nice ^^ There doesn't seem to be any low-hanging fruits now.

2023-04-12 13:54 UTC, krdln commented on pkg/policies/flowcontrol/service/checkhttp/checkhttp.go
> +					values.Insert(ast.StringTerm(name),
Disregard – LazyObject will unlazy itself as soon as its inserted to another object, so it doesn't make sense.

2023-04-12 15:47 UTC, DariaKunoichi commented on pkg/policies/flowcontrol/service/envoy/authz.go
> -	}
Done

2023-04-13 09:18 UTC, krdln approved these changes

2023-04-13 09:18 UTC, krdln commented on pkg/policies/flowcontrol/resources/classifier/classifier_test.go
>  	}
Actually, since this whole function is not performance sensitive, you can leave the original one and just wrap the whole in `MustInterfaceToObject`.

2023-04-13 14:19 UTC, merged