Unify TLS config
fluxninja/aperture pull request #375
Opened 2022-09-08 13:04 UTC by jmichalak-fluxninja

2022-09-09 14:52 UTC, harjotgill approved these changes

2022-09-10 15:12 UTC, harjotgill requested changes

2022-09-10 15:12 UTC, harjotgill commented on pkg/net/tlsconfig/server.go
> +	if err := unmarshaller.UnmarshalKey(constructor.ConfigKey, &config); err != nil {
Why repeat this code? Can't we just provide this to provide TLS function and remove repetition? Or have the provide TLS function return config as well.

2022-09-12 13:45 UTC, kwapik approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fluxninja/aperture/375)* status: all files reviewed, 1 unresolved discussion (waiting on @jmichalak-fluxninja)



<!-- Sent from Reviewable.io -->

2022-09-14 15:08 UTC, harjotgill approved these changes

2022-09-15 07:59 UTC, merged